# model-storage.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo