apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  labels:
    app: ollama-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 11434
    targetPort: 11434
    protocol: TCP
    name: http
  selector:
    app: ollama-deployment